### ISSUE TITLE
It is calling the timezones multiple times

### ISSUE THREAD

**Issue by equiman** [deinsoftware/fun-with-flags#30]
# Steps

- Go to create an event
- Open country list
- Don't stop making requests after closing the modal window

# Evidence

![image](https://github.com/deinsoftware/fun-with-flags/assets/933393/74b2441a-60e4-44ae-bfc0-f687d26bc439)

**Comment by MrRedu** [comment]
# Issue:
Todo comienza en el componente, donde en cada renderizado se ejecuta el hook `useFetch`.
Dentro de `useFetch`, por cada renderizado se ejecuta el efecto, ya que la dependencia date siempre es nueva.
El efecto hace un fetch llamando a `getAllTimeZones`. Esta función asincrónica retorna una `Promise`.
El problema surge aquí: mientras esa `Promise` está pendiente, no se actualiza el estado data en `useFetch`.
Como `data` no cambia, el componente vuelve a renderizarse, volviendo a ejecutar `useFetch` y el efecto.
Esto dispara otra llamada a `getAllTimeZones` antes de que siquiera se haya resuelto la primera.
De esta forma se va acumulando un **bucle infinito de llamadas a la API**, donde cada llamada desencadena una nueva llamada sin esperar la respuesta anterior.
# Solution:
Para evitar volver a ejecutar el efecto mientras haya una petición pendiente, lo hacemos mediante un estado loading como implementamos.
Así rompemos el ciclo infinito, ya que loading impide que se ejecute el fetch repetidamente.
Solved in Pull Request: #33

```js
useEffect(() => {

  if (loading) return
  setLoading(true)
  ...
}
```
# Evidence:
![image](https://github.com/deinsoftware/fun-with-flags/assets/73679190/39ef842f-e11a-44a1-86f3-da24cd4adb73)

**Comment by equiman** [comment]
Also, need to include abort control to cancel requests when the component did unmount.

https://developer.chrome.com/blog/abortable-fetch/#one-signal-many-fetches
