### ISSUE TITLE
Double hashtag

### ISSUE THREAD

**Issue by Alexis033** [deinsoftware/fun-with-flags#90]
Two repeated hashtags are allowed when using the "," and cannot be deleted.

Steps to reproduce:
- Write two hashtags with a comma
- Press the return key or click the add button 

![image](https://github.com/deinsoftware/fun-with-flags/assets/110948692/d9f16f24-62b1-4f40-bbb5-62501c6fda4d)

**Comment by equiman** [comment]
Fixed adding a unique list of tags, removing duplicated values:

![image](https://github.com/deinsoftware/fun-with-flags/assets/933393/81d4c54d-d45b-489b-a219-c1724eabb13e)
